#Main - Left, Other - Right
#LVDS-1 VGA-1

Section "Monitor"
	Identifier	"LVDS-1"
	#Option		"Primary"	"true"
EndSection
Section "Monitor"
	Identifier	"VGA-1"
	Option		"leftof"	"LVDS-1"
	Option		"Primary"	"true"
EndSection
